### ISSUE TITLE
printf and similar functions do not work

### ISSUE THREAD

**Issue by pedzed** [QQuick/Cantino#2]
```cpp
#include <cantino.h>

using namespace cantino;

int main()
{
    cout << "cout does work" << endl;
    printf("printf does %s work\n", "not(?)");
    
    return 0;
}
```

Results in:
```
cout does work
```

Expected:
```
cout does work
printf does not(?) work
```

Although I have not tested it, I am sure other similar print functions do not work either.

**Comment by JdeH** [comment]
Functions printf, scanf etc. have not been added to Cantino, to keep it small, since the Arduino Uno has very little memory.
The streams cout en cin are the C++ way to go in this course.

**Comment by pedzed** [comment]
That's unfortunate considering that `printf` is quite powerful. Any possibility to perhaps have it as an optional dependency?

**Comment by pedzed** [comment]
That's unfortunate considering that `printf` is quite powerful. Any possibility to perhaps have it as an optional dependency?

It's a bit ugly and inefficient (coding/reading wise) to construct console outputs or strings in general like this:

```c++
cout << "(X: " << primaryJoystick.getHorizontalValue() << ",";
cout << " Y: " << primaryJoystick.getVerticalValue() << ")";
cout << " | neutral: " << primaryJoystick.isNeutral();
cout << " | pressing: " << primaryJoystick.isPressing() << endl;
```

**Comment by JdeH** [comment]
Currently Cantino is a tiny library facilitating working on the Arduino without explicitly addressing the serial port or working with setup () and loop ().

In order for stdio.h / stdio.cpp to work on the Arduino it would have to be severerly stripped down, missing all kinds of advanced formatting options. Suppose it would just support %s, %f, %i, %c etc, but no formatting (nr of digits, precission, padding chars etc.), would it then still be useful to you?

**Comment by pedzed** [comment]
> Suppose it would just support %s, %f, %i, %c etc, but no formatting (nr of digits, precission, padding chars etc.)

That would be nice, yes. But how will it be documented? Will an exception be thrown if somebody tries do use the advanced formatting options?

And will you be able to save the constructed string to a variable rather than printing it directly to the console, like [`snprintf`](http://www.cplusplus.com/reference/cstdio/snprintf/)? That would be particularly useful for TFT/OLED/LCD displays.

**Comment by JdeH** [comment]
OK, noted. For the time being will just leave it at cin and cout.
